# ? Azure persistent DB (FIX)
spring.datasource.url=jdbc:h2:file:/home/site/wwwroot/data/courtcase-db;AUTO_SERVER=TRUE

spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# ? JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# ? Disable H2 console (Azure)
spring.h2.console.enabled=false

server.port=8080